### ISSUE TITLE
I fail to suppress logging output

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.climate.stress.test#161]
I fail to use this option to suppress the logging output:

r2dii.climate.stress.verbose_log_env

I see we can set this option but doing so has no effect on
the behaviour of `run_stress_test()`. 

Did we forget to add something like this in the body of
`run_stress_test()`?

```r
if (is_verbose_log_env()) "be verbose" else "be quiet"
```

**Comment by MirijaHa** [comment]
Great example for the bug or feature discussion we just had :)
My requirement was that the verbose diagnostics (currently only "Missing 123 rows on") be supressable. The remaining few logs lines should print. Given that our code is a pipeline in its nature I find it adequate to logs the information as status updates (code might run much longer on user projects).

**Comment by maurolepore** [comment]
Oh, I see -- `is_verbose_log_env()` is used in `report_missing()`. 

https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/9bbb1dce2da174d4a7ad97ea695cd57f4f744cf4/R/utils.R#L250

I missed that hit before. Sorry.
