### ISSUE TITLE
Can users run out of memory?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.climate.stress.test#178]
Can the data get large? Can the users run out of memory if this list holds too many runs of too large datasets?

If so we should instead write the results of each run before moving on to the next run.

_Originally posted by @maurolepore in https://github.com/2DegreesInvesting/r2dii.climate.stress.test/pull/175#r745950221_

**Comment by MirijaHa** [comment]
I was wondering about that too.
As an empiric reference, we formerly had larger outputs than currently and a default of 11 iterations and did not run into memory problem.
Problem is it is not predictable how large dataset will get as this depends on the size of the underlying portfolio.
