### ISSUE TITLE
`set_params_st.R` needed for webtools

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.climate.stress.test#235]
@MirijaHa #233 breaks the web tools my removing `R/set_params_st.R`, which is sourced here:
https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/05c9d2ec313a0f31c132c0f36187f1c6d5a3c9ba/web_tool_external_stress_test.R#L27
and here:
https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/05c9d2ec313a0f31c132c0f36187f1c6d5a3c9ba/web_tool_stress_test.R#L43

**Comment by MirijaHa** [comment]
Thanks for noticing.
The function that is defined in the file `set_project_parameters` is not called from web_tool_external_stress_test.R and web_tool_stress_test.R, which is why I did not notice. I will open a follow up that removes the lines you posted.
