### ISSUE TITLE
Improve example on website

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.climate.stress.test#352]
Currently you use strings "/path/to/specific/data" and "/path/to/agnostic/data" as placeholders for user's path. It makes it a bit tedious to run the example. My proposal is to assign them to variables so that once the user has the variables with the right paths in their environment, they can just copy your code. Like so:

```
path_to_specific_data <- "/path/to/specific/data"
path_to_agnostic_data <- "/path/to/agnostic/data"

run_prep_calculation_loans(
  input_path_project_specific = path_to_specific_data,
  input_path_project_agnostic = path_to_agnostic_data,
  data_prep_output_path = path_to_specific_data
)
```

**Comment by MirijaHa** [comment]
If it is ok with you I would close this issue. We will use toy data included in the package in the example the the website so there will be no more need to provide filepaths.

**Comment by MonikaFu** [comment]
Yes! Sounds good.
