### ISSUE TITLE
Portfolio with no PACTA relevant data will error out

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.climate.stress.test#354]
If you have a portfolio with equity holdings, but none that are in PACTA relevant sectors and none that have PACTA relevant assets, the stress test will fail here with an error...

https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/15f72a55a5358a80cbc89eedbc10ecd912de06b4/web_tool_stress_test.R#L248-L255

```r
Error in `check_portfolio_consistency()`:
! Start year of the analysis and first year in the input portfolio do not match.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In min(df$year, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
```

The `dplyr` chain leading to the `check_portfolio_consistency()` function will pass a data.frame with zero rows, causing `check_portfolio_consistency()` to return the error.

Here is an example portfolio that will cause this error...
```
Investor.Name,Portfolio.Name,ISIN,MarketValue,Currency
test,test,LU0061462528,1000000,EUR
```

Note, that [a similar bug exists in the TDM code](https://github.com/2DegreesInvesting/pacta.portfolio.analysis/issues/17) in PACTA_analysis, so you will need to use a project code in the project parameters file other than "GENERAL", e.g. "PA2021LU", in order to replicate this error.

**Comment by MirijaHa** [comment]
Dear @cjyetman 
for prioritisation of fixing this, can you quickly summarise what the consequences of the bug are currently on transition monitor?

**Comment by MirijaHa** [comment]
FYI @jacobvjk , @cjyetman will prevent calculation of portfolios without pacta relevant sectors from pacta side so no need for us to do anything.

**Comment by MirijaHa** [comment]
No longer relavant
