### ISSUE TITLE
possible bug in web_tool_stress_test.R

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.climate.stress.test#45]
https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/60d050481c24d81b3b1f0206b7abb17e77c6ed19/web_tool_stress_test.R#L296-L299

After a lot of experimentation and testing, I believe the code above is flawed and can lead to errors as it can cause `pacta_equity_results_full` to have duplicate lines in terms of `nesting_vars` if `pacta_equity_results_full$scenario` contains values that are different if complete, but the same after the prepended scenario source name is removed. This is a plausible situation. The normal PACTA results do not include a `scenario_source` column, hence the need to prepend the scenario source to the scenario name so that they are distinguishable. In the current 2020Q4 testing that I'm doing, `pacta_equity_results_full$scenario` includes e.g. "ETP2017_NPS" and "WEO2019_NPS", which both become "NPS" after the lines above, leading to indistinguishable lines and a whole lot of mess downstream. And the code here explicitly allows for this situation...
https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/60d050481c24d81b3b1f0206b7abb17e77c6ed19/web_tool_stress_test.R#L93-L104

```
pacta_equity_results_full$scenario %>% unique()
# [1] "ETP2017_B2DS" "ETP2017_NPS"  "ETP2017_SDS"  "WEO2019_CPS"  "WEO2019_NPS" 
# [6] "WEO2019_SDS"  NA       

nesting_vars
# [1] "investor_name"      "portfolio_name"     "equity_market"     
# [4] "ald_sector"         "technology"         "scenario"          
# [7] "allocation"         "scenario_geography"
```

I believe this is the root of the problem we discussed today @jacobvjk @MirijaHa @AlexAxthelm @jdhoffa

**Comment by cjyetman** [comment]
For further clarity... `pacta_equity_results_full` starts as data read in directly from PACTA outputs. This slicing of the scenario name happens immediately after, and the problem already exists at that point as long as the imported PACTA results include "ETP2017_NPS" and "WEO2019_NPS" and/or "ETP2017_SDS" and "WEO2019_SDS"


https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/60d050481c24d81b3b1f0206b7abb17e77c6ed19/web_tool_stress_test.R#L288-L299

**Comment by cjyetman** [comment]
With a test file I gave to @jacobvjk privately for instance...

``` r
pacta_equity_results_full <- readRDS("Equity_results_portfolio.rda")

pacta_equity_results_changed <-
  pacta_equity_results_full %>%
  filter(scenario %in% scenarios) %>%
  mutate(scenario = ifelse(str_detect(scenario, "_"), str_extract(scenario, "[^_]*$"), scenario))


pacta_equity_results_full$scenario %>% unique()
# [1] "ETP2017_B2DS" "ETP2017_NPS"  "ETP2017_SDS"  "WEO2019_CPS"  "WEO2019_NPS" 
# [6] "WEO2019_SDS"  NA   

pacta_equity_results_changed$scenario %>% unique()
# [1] "B2DS" "NPS"  "SDS"  "CPS" 


pacta_equity_results_full %>% 
  group_by(scenario) %>% 
  summarise(n = n())
# # A tibble: 7 × 2
#   scenario         n
#   <chr>        <int>
# 1 ETP2017_B2DS  1134
# 2 ETP2017_NPS    630
# 3 ETP2017_SDS    126
# 4 WEO2019_CPS    630
# 5 WEO2019_NPS    630
# 6 WEO2019_SDS    630
# 7 NA               1

pacta_equity_results_changed %>% 
  group_by(scenario) %>% 
  summarise(n = n())
# # A tibble: 4 × 2
#   scenario     n
#   <chr>    <int>
# 1 B2DS      1134
# 2 CPS        630
# 3 NPS       1260
# 4 SDS        756
```

**Comment by cjyetman** [comment]
possibly closed by #47?

**Comment by MirijaHa** [comment]
Exactly, this is where this new friend comes into play https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/91af92f236b1b57ef1213f770668de81cae2da44/R/utils.R#L176
We will start improvements on the web scripts once we are done with the user scripts which are priority atm. As the concrete issue is "solved" would you be fine to close this issue? :)

**Comment by cjyetman** [comment]
I believe the intent of this bug report has been resolved. I agree with @jdhoffa that #47 is not a great solution, however, I do believe that the Stress Testing tool should be resilient to changes in the data that are not necessarily expected. I don't think it's necessarily "wrong" that the data that revealed this issue has rows where `scenario == "ETP2017_NPS" & ald_sector == "Power"`.

**Comment by jdhoffa** [comment]
Woo!
