### ISSUE TITLE
BUG: duplicate rows introduced for NPS from multiple sources

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/r2dii.climate.stress.test#46]
https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/60d050481c24d81b3b1f0206b7abb17e77c6ed19/web_tool_stress_test.R#L296-L299

If an input data set has ETP2017_NPS and WEO2019_NPS for the same technologies, this will lead to ambiguous rows in the data.
We need an additional step, that clarifies we only want Automotive from ETP and everything else from WEO.

**Comment by cjyetman** [comment]
related to (or supersedes?) #45

**Comment by cjyetman** [comment]
possibly closed by #47?

**Comment by MirijaHa** [comment]
fixed
