### ISSUE TITLE
merge data_path() and get_st_data_path() into single function

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/r2dii.climate.stress.test#8]
`data_path()` returns `data-raw/...` by default. `data-raw` can theoretically be changed for something else.. `...` can be an arbitrary number of additional levels and the ultimate file name to be retrieved. so in that sense it is supposed to be used as something returning a relative path within a repo/package/... 
so this should be good as long as the target directory retrieved from `get_st_data_path()` points to the top level of a repo/package or something structured like that.
But I admit I am wondering how reasonable it is to even make two functions out of those.

_Originally posted by @jacobvjk in https://github.com/2DegreesInvesting/r2dii.climate.stress.test/pull/7#discussion_r644720332_

**Comment by MirijaHa** [comment]
outdated
